#!/usr/bin/env bash
#Script displays a different info for 4th and 8th iterations

i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((++i))
done
